<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0;net10.0;net11.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
    <TieredPGO>true</TieredPGO>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <WarningsAsErrors>$(WarningsAsErrors);NU1605;</WarningsAsErrors>
    <NoWarn>$(NoWarn);CS1591;CS8604;CS8032;CS8002;CS8600</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <WarningsAsErrors>$(WarningsAsErrors);NU1605;</WarningsAsErrors>
    <NoWarn>$(NoWarn);CS1591;CS8604;CS8032;CS8002;CS8600</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
    <PackageReference Include="BinaryPack" />
    <PackageReference Include="K4os.Compression.LZ4" />
    <PackageReference Include="K4os.Compression.LZ4.Streams" />
    <PackageReference Include="MessagePack" />
    <PackageReference Include="MessagePackAnalyzer">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Orleans.CodeGenerator">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Orleans.Serialization" />
    <PackageReference Include="protobuf-net" />
    <PackageReference Include="System.IO.Pipelines" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\MemoryPack.Core\MemoryPack.Core.csproj" />
    <ProjectReference Include="..\..\src\MemoryPack.Generator\MemoryPack.Generator.csproj">
      <OutputItemType>Analyzer</OutputItemType>
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <Using Include="BenchmarkDotNet.Attributes" />
  </ItemGroup>
</Project>
