<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net8.0;net10.0;net11.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <NoWarn>$(NoWarn);CS1591;CA2255</NoWarn>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

		    <!-- NuGet -->
        <IsPackable>true</IsPackable>
        <PackageTags>serializer</PackageTags>
        <Description>Additional streaming support for MemoryPack.</Description>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="System.IO.Pipelines" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\MemoryPack.Core\MemoryPack.Core.csproj" />
    </ItemGroup>

</Project>
